[package]
name = "race-solana"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
solana-program = "1.5.6"
spl-token = { version = "3.0.1", features = ["no-entrypoint"] }
borsh = "0.9.3"
arrayref = "0.3.6"
thiserror = "1.0.35"

[dev-dependencies]
anyhow = "1.0.64"
